INSERT INTO Shop (decorationNAme, price, category)
VALUES 
	("Wall Color - White", 0, 'wall'),
	("Wall Color - Blue", 5, 'wall'),
	("Wall Color - Orange", 5, 'wall'),
	("Wall Color - Floral", 10, 'wall'),
	("Wall Color - Stripes", 10, 'wall'),
	("Wall Color - Cat Paper", 25, 'wall'),
	("White Cushion", 5, 'cushion'),
	("Blue Cushion", 10, 'cushion'),
	("Red Cushion", 10, 'cushion'),		
	("Tree Design Cushion", 25, 'cushion'),
	("Cat Cushion", 50, 'cushion'),
	("White Carpet", 0, 'carpet'),
	("Navy Blue Carpet", 5, 'carpet'),
	("Maroon Carpet", 5, 'carpet'),
	("Linoleum Carpet", 10, 'carpet'),
	("Wood Carpet", 10, 'carpet'),
	("Cat Tiles", 25, 'carpet'),
	("Clock - Blue", 5, 'clock'),
	("Clock - Red", 5, 'clock'),
	("Clock - Black", 15, 'clock'),
	("Clock - White", 15, 'clock'),
	("Clock - Cat", 30, 'clock');
